-- MySQL Script generated by MySQL Workbench
-- Sat Aug 10 18:19:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hospital_db_Lucas_Vinicius
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital_db_Lucas_Vinicius
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital_db_Lucas_Vinicius` DEFAULT CHARACTER SET utf8 ;
USE `hospital_db_Lucas_Vinicius` ;

-- -----------------------------------------------------
-- Table `hospital_db_Lucas_Vinicius`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db_Lucas_Vinicius`.`pacientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `data_nasci` DATE NOT NULL,
  `endereco` VARCHAR(250) NOT NULL,
  `rg` VARCHAR(13) NOT NULL,
  `cpf` VARCHAR(14) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_db_Lucas_Vinicius`.`convenios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db_Lucas_Vinicius`.`convenios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `cnpj` VARCHAR(18) NOT NULL COMMENT '99.999.999/9999-99',
  `carencia` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_db_Lucas_Vinicius`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db_Lucas_Vinicius`.`medicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `data_nasc` DATE NOT NULL COMMENT '99/99/9999',
  `cpf` VARCHAR(14) NOT NULL COMMENT '999.999.999-99',
  `crm` VARCHAR(25) NOT NULL,
  `uf_crm` VARCHAR(2) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL COMMENT '(99)9 9999-9999',
  `endereco` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_db_Lucas_Vinicius`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db_Lucas_Vinicius`.`especialidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_db_Lucas_Vinicius`.`especialidades_medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db_Lucas_Vinicius`.`especialidades_medicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `medico_id` INT NOT NULL,
  `especialidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_medico_especmedicos_idx` (`medico_id` ASC) VISIBLE,
  INDEX `fk_especialidade_especmedicos_idx` (`especialidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_medico_especmedicos`
    FOREIGN KEY (`medico_id`)
    REFERENCES `hospital_db_Lucas_Vinicius`.`medicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_especialidade_especmedicos`
    FOREIGN KEY (`especialidade_id`)
    REFERENCES `hospital_db_Lucas_Vinicius`.`especialidades` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_db_Lucas_Vinicius`.`consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db_Lucas_Vinicius`.`consultas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_hora` DATETIME NOT NULL,
  `medico_id` INT NOT NULL,
  `paciente_id` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `convenio_id` INT NULL,
  `carteira_convenio` VARCHAR(25) NULL,
  `especmedico_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_consultas_pacientes1_idx` (`paciente_id` ASC) VISIBLE,
  INDEX `fk_consultas_medicos1_idx` (`medico_id` ASC) VISIBLE,
  INDEX `fk_especmedico_consultas_idx` (`especmedico_id` ASC) VISIBLE,
  INDEX `fk_convenios_consultas_idx` (`convenio_id` ASC) VISIBLE,
  CONSTRAINT `fk_paciente_consultas`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `hospital_db_Lucas_Vinicius`.`pacientes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_medico_consultas`
    FOREIGN KEY (`medico_id`)
    REFERENCES `hospital_db_Lucas_Vinicius`.`medicos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_especmedico_consultas`
    FOREIGN KEY (`especmedico_id`)
    REFERENCES `hospital_db_Lucas_Vinicius`.`especialidades_medicos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_convenio_consultas`
    FOREIGN KEY (`convenio_id`)
    REFERENCES `hospital_db_Lucas_Vinicius`.`convenios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_db_Lucas_Vinicius`.`receitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db_Lucas_Vinicius`.`receitas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `medicamentos receitados` VARCHAR(600) NOT NULL,
  `consulta_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_receitas_consultas1_idx` (`consulta_id` ASC) VISIBLE,
  CONSTRAINT `fk_consulta_receitas`
    FOREIGN KEY (`consulta_id`)
    REFERENCES `hospital_db_Lucas_Vinicius`.`consultas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_db_Lucas_Vinicius`.`tipos_quartos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db_Lucas_Vinicius`.`tipos_quartos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(500) NOT NULL,
  `valor_diario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_db_Lucas_Vinicius`.`quartos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db_Lucas_Vinicius`.`quartos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `tipo_quarto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tipoquarto_quartos_idx` (`tipo_quarto_id` ASC) VISIBLE,
  CONSTRAINT `fk_tipoquarto_quartos`
    FOREIGN KEY (`tipo_quarto_id`)
    REFERENCES `hospital_db_Lucas_Vinicius`.`tipos_quartos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_db_Lucas_Vinicius`.`internacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db_Lucas_Vinicius`.`internacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_entrada` DATE NOT NULL,
  `data_prev_alta` DATE NOT NULL,
  `data_alta` DATE NOT NULL,
  `desc_procedimento` VARCHAR(1000) NOT NULL,
  `medico_id` INT NOT NULL,
  `paciente_id` INT NOT NULL,
  `quarto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_medico_interncoes_idx` (`medico_id` ASC) VISIBLE,
  INDEX `fk_paciente_internacoes_idx` (`paciente_id` ASC) VISIBLE,
  INDEX `fk_quarto_internacoes_idx` (`quarto_id` ASC) VISIBLE,
  CONSTRAINT `fk_medico_internacoes`
    FOREIGN KEY (`medico_id`)
    REFERENCES `hospital_db_Lucas_Vinicius`.`medicos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_paciente_internacoes`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `hospital_db_Lucas_Vinicius`.`pacientes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_quarto_internacoes`
    FOREIGN KEY (`quarto_id`)
    REFERENCES `hospital_db_Lucas_Vinicius`.`quartos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_db_Lucas_Vinicius`.`enfermeiros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db_Lucas_Vinicius`.`enfermeiros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `cre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_db_Lucas_Vinicius`.`enfermeiros_internacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db_Lucas_Vinicius`.`enfermeiros_internacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `internacao_id` INT NOT NULL,
  `enfermeiro_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_internacao_requerenf_idx` (`internacao_id` ASC) VISIBLE,
  INDEX `fk_enfermeiro_requerenf_idx` (`enfermeiro_id` ASC) VISIBLE,
  CONSTRAINT `fk_internacao_enfinter`
    FOREIGN KEY (`internacao_id`)
    REFERENCES `hospital_db_Lucas_Vinicius`.`internacoes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_enfermeiro_enfinter`
    FOREIGN KEY (`enfermeiro_id`)
    REFERENCES `hospital_db_Lucas_Vinicius`.`enfermeiros` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
